import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from '@/components/Header/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {

  // Variaveis

  const data = new Date()

  // Rendering

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
          
          min-h-screen flex flex-col items-center justify-start p-20 gap-2
          `} 
      >
        <Header />
        <main className="bg-blue-200 p-5 rounded-2xl min-h-[70vh] 
                          w-full md:w-2/3 lg:w-1/2 xl:w-1/3">
          {children}
        </main>
        <footer>DIW, {data.getFullYear()}</footer>
      </body>
    </html>
  );
}
